<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6NI868R" ignored="0" name="RetryMulitpleFailedTestCases" tests="9" failures="2" timestamp="06 Sep 2019 12:54:55 GMT" time="0.125" errors="0">
  <testcase name="Test1" time="0.015" classname="RetryLogicTestNG.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="RetryLogicTestNG.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="RetryLogicTestNG.MyTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.0" classname="RetryLogicTestNG.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicTestNG.MyTests.Test1(MyTests.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="RetryLogicTestNG.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="RetryLogicTestNG.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="RetryLogicTestNG.MyTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="RetryLogicTestNG.MyTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RetryLogicTestNG.MyTests.Test2(MyTests.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.0" classname="RetryLogicTestNG.MyTests"/>
</testsuite> <!-- RetryMulitpleFailedTestCases -->
